-- =============================================
-- CLEAN: Remove all data generated by db_seed_test.sql
-- Targets email domain @panelatletas.test only
-- Cascade from auth.users → users_profiles → athletes, users_disciplines, medals
-- users_invitations deleted explicitly (fk_invited_by is SET NULL on cascade, not deleted)
-- =============================================

BEGIN;

-- Delete test invitations first (fk_invited_by SET NULL on parent delete, not cascaded)
DELETE FROM public.users_invitations
WHERE email LIKE '%@panelatletas.test';

-- Delete test auth users — cascades to:
--   users_profiles → athletes, users_disciplines, medals
DELETE FROM auth.users
WHERE email LIKE '%@panelatletas.test';

COMMIT;
