TRUNCATE public.disciplines CASCADE;

INSERT INTO public.disciplines (name, discipline_type, is_active) VALUES
  ('Ajedrez',       'sport',        TRUE),
  ('Ajedrez',       'recreational', TRUE),
  ('Atletismo',     'sport',        TRUE),
  ('Atletismo',     'recreational', TRUE),
  ('Judo',          'sport',        TRUE),
  ('Judo',          'recreational', TRUE),
  ('Karate Do',     'sport',        TRUE),
  ('Karate Do',     'recreational', TRUE),
  ('Taekwondo',     'sport',        TRUE),
  ('Taekwondo',     'recreational', TRUE),
  ('Tenis de Mesa', 'sport',        TRUE),
  ('Tenis de Mesa', 'recreational', TRUE),
  ('Triatlón',      'sport',        TRUE),
  ('Triatlón',      'recreational', TRUE),
  ('Zumba',         'sport',        TRUE),
  ('Zumba',         'recreational', TRUE),
  ('Funcionales',   'sport',        TRUE),
  ('Funcionales',   'recreational', TRUE),
  ('Yoga',          'sport',        TRUE),
  ('Yoga',          'recreational', TRUE),
  ('Adulto Mayor',  'sport',        TRUE),
  ('Adulto Mayor',  'recreational', TRUE),
  ('Baloncesto',    'sport',        TRUE),
  ('Baloncesto',    'recreational', TRUE),
  ('Voleibol',      'sport',        TRUE),
  ('Voleibol',      'recreational', TRUE),
  ('Boxeo',         'sport',        TRUE),
  ('Boxeo',         'recreational', TRUE),
  ('Futbol Sala',   'sport',        TRUE),
  ('Futbol Sala',   'recreational', TRUE),
  ('Fútbol',        'sport',        TRUE),
  ('Fútbol',        'recreational', TRUE);
